export const stageStats = [{ stage: 'Pokémon Stadium 2',
  shortName: 'PS2',
  gamesPlayed: 777,
  setsPlayed: 705,
  gamesBanned: 62,
  setsBanned: 62,
  starter: true },{ stage: 'Smashville',
  shortName: 'SV',
  gamesPlayed: 281,
  setsPlayed: 273,
  gamesBanned: 112,
  setsBanned: 110,
  starter: true },{ stage: 'Battlefield',
  shortName: 'BF',
  gamesPlayed: 425,
  setsPlayed: 394,
  gamesBanned: 169,
  setsBanned: 166,
  starter: true },{ stage: 'Final Destination',
  shortName: 'FD',
  gamesPlayed: 217,
  setsPlayed: 207,
  gamesBanned: 299,
  setsBanned: 291,
  starter: true },{ stage: 'Lylat Cruise',
  shortName: 'Lylat',
  gamesPlayed: 58,
  setsPlayed: 57,
  gamesBanned: 383,
  setsBanned: 356,
  starter: true },{ stage: 'Town And City',
  shortName: 'T&C',
  gamesPlayed: 128,
  setsPlayed: 122,
  gamesBanned: 85,
  setsBanned: 84,
  starter: false },{ stage: 'Unova Pokémon League',
  shortName: 'Unova',
  gamesPlayed: 54,
  setsPlayed: 52,
  gamesBanned: 119,
  setsBanned: 117,
  starter: false },{ stage: "Yoshi's Island (Brawl)",
  shortName: 'Y.Island',
  gamesPlayed: 51,
  setsPlayed: 51,
  gamesBanned: 302,
  setsBanned: 291,
  starter: false },{ stage: 'Kalos Pokémon League',
  shortName: 'Kalos',
  gamesPlayed: 92,
  setsPlayed: 92,
  gamesBanned: 195,
  setsBanned: 193,
  starter: false },{ stage: "Yoshi's Story",
  shortName: 'Y.Story',
  gamesPlayed: 109,
  setsPlayed: 109,
  gamesBanned: 185,
  setsBanned: 182,
  starter: false },{ stage: 'Castle Siege',
  shortName: 'C.Siege',
  gamesPlayed: 45,
  setsPlayed: 45,
  gamesBanned: 629,
  setsBanned: 584,
  starter: false },];

export const globalStats = { totalGames: 2237,
  totalSets: 1140,
  totalBans: 2540,
  setsWithBanRecorded: 1032 };