export const stageStats = [{ stage: 'Pokémon Stadium 2',
  shortName: 'PS2',
  gamesPlayed: 428,
  setsPlayed: 360,
  gamesBanned: 29,
  setsBanned: 27,
  starter: true },{ stage: 'Smashville',
  shortName: 'SV',
  gamesPlayed: 124,
  setsPlayed: 114,
  gamesBanned: 92,
  setsBanned: 90,
  starter: true },{ stage: 'Battlefield',
  shortName: 'BF',
  gamesPlayed: 161,
  setsPlayed: 149,
  gamesBanned: 117,
  setsBanned: 116,
  starter: true },{ stage: 'Final Destination',
  shortName: 'FD',
  gamesPlayed: 79,
  setsPlayed: 75,
  gamesBanned: 201,
  setsBanned: 187,
  starter: true },{ stage: 'Lylat Cruise',
  shortName: 'Lylat',
  gamesPlayed: 37,
  setsPlayed: 37,
  gamesBanned: 172,
  setsBanned: 170,
  starter: false },{ stage: 'Town And City',
  shortName: 'T&C',
  gamesPlayed: 139,
  setsPlayed: 135,
  gamesBanned: 44,
  setsBanned: 44,
  starter: true },{ stage: "Yoshi's Island (Brawl)",
  shortName: 'Y.Island',
  gamesPlayed: 20,
  setsPlayed: 20,
  gamesBanned: 218,
  setsBanned: 210,
  starter: false },{ stage: 'Kalos Pokémon League',
  shortName: 'Kalos',
  gamesPlayed: 64,
  setsPlayed: 62,
  gamesBanned: 140,
  setsBanned: 140,
  starter: false },{ stage: "Yoshi's Story",
  shortName: 'Y.Story',
  gamesPlayed: 31,
  setsPlayed: 31,
  gamesBanned: 141,
  setsBanned: 135,
  starter: false },];

export const globalStats = { totalGames: 1083,
  totalSets: 535,
  totalBans: 1154,
  setsWithBanRecorded: 466 };

export const stages = [ 'Pokémon Stadium 2',
  'Smashville',
  'Battlefield',
  'Final Destination',
  'Lylat Cruise',
  'Town And City',
  "Yoshi's Island (Brawl)",
  'Kalos Pokémon League',
  "Yoshi's Story" ];

export const shortNames = [ 'PS2',
  'SV',
  'BF',
  'FD',
  'Lylat',
  'T&C',
  'Y.Island',
  'Kalos',
  'Y.Story' ];